import unittest


def sumOfMultiples( n: int) -> int:
    ans = 0
    for x in range(1, n + 1):
        if x % 3 == 0 or x % 5 == 0 or x % 7 == 0:
            ans += x

    return ans

#Generated by Chat GPT

# class TestSumOfMultiples(unittest.TestCase):

#     def test_sum_of_multiples(self):
#         # Replace YourClass with the actual class name
#
#         # Test Case 1
#         self.assertEqual(sumOfMultiples(10), 33)
#
#         # Test Case 2
#         self.assertEqual(sumOfMultiples(20), 98)
#
#         # Test Case 3
#         self.assertEqual(sumOfMultiples(5), 8)
#
#         # Test Case 4
#         self.assertEqual(sumOfMultiples(15), 45)
#
#         # Test Case 5
#         self.assertEqual(sumOfMultiples(1), 0)
#
#
# if __name__ == '__main__':
#     unittest.main()


##Remarks
# Didn't understand that the code was to give out mutliples of 3, 5, or 7 from [1, n] with n inclusive. ' \
# It gave out test cases with n excluded. Also it was just random


class CorrectTestSumOfMultiples(unittest.TestCase):

    def test_sum_of_multiples(self):
        # Replace YourClass with the actual class name

        # Test Case 1
        self.assertEqual(sumOfMultiples(10), 40)

        # Test Case 2
        self.assertEqual(sumOfMultiples(20), 119)

        # Test Case 3
        self.assertEqual(sumOfMultiples(5), 8)

        # Test Case 4
        self.assertEqual(sumOfMultiples(15), 81)

        # Test Case 5
        self.assertEqual(sumOfMultiples(1), 0)


if __name__ == '__main__':
    unittest.main()
